# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 间隔4小时任务

on:
  workflow_dispatch:
  schedule:
    - cron: '1 0,4,10,16,22 * * *'
  watch:
    types: started
  repository_dispatch:
    types: job_3_hour
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      run: |
        git clone ${{ secrets.GIT_CLONE_URL }} ~/scripts
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install
      run: |
        cd ~/scripts
        npm install
    - name: '运行 【宠汪汪积分兑换京豆】'
      run: |
        cd ~/scripts
        node jd_joy_reward.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        JD_JOY_REWARD_NOTIFY: ${{ secrets.JD_JOY_REWARD_NOTIFY }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}

    - name: '运行 【东东农场】'
      run: |
        cd ~/scripts
        node jd_fruit.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        FRUITSHARECODES: ${{ secrets.FRUITSHARECODES }}
        FRUIT_BEAN_CARD: ${{ secrets.FRUIT_BEAN_CARD }}
        FRUIT_NOTIFY_CONTROL: ${{ secrets.FRUIT_NOTIFY_CONTROL }}

    - name: '运行 【京喜农场】'
      run: |
        cd ~/scripts
        node jd_jxnc.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        FRUITSHARECODES: ${{ secrets.FRUITSHARECODES }}
        FRUIT_BEAN_CARD: ${{ secrets.FRUIT_BEAN_CARD }}
        FRUIT_NOTIFY_CONTROL: ${{ secrets.FRUIT_NOTIFY_CONTROL }}

    - name: '运行 【宠汪汪偷好友狗粮与积分】'
      run: |
        cd ~/scripts
        node jd_joy_steal.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        JOY_HELP_FEED: ${{ secrets.JOY_HELP_FEED }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}

    - name: '运行 【京喜财富岛】'
      run: |
        cd ~/scripts
        node jd_jxcfd.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}

    - name: '运行 【京东直播】'
      run: |
        cd ~/scripts
        node jd_live.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}

    - name: '运行 【京东摇钱树】'
      run: |
        cd ~/scripts
        node jd_moneyTree.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}

    - name: '运行 【东东超市】'
      run: |
        cd ~/scripts
        node jd_superMarket.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        jdSuperMarketUpgrade: ${{ secrets.SUPERMARKET_UPGRADE }}
        jdBusinessCircleJump: ${{ secrets.BUSINESS_CIRCLE_JUMP }}
        SUPERMARKET_SHARECODES: ${{ secrets.SUPERMARKET_SHARECODES }}
        jdSuperMarketLottery: ${{ secrets.SUPERMARKET_LOTTERY }}

    - name: '运行 【5G狂欢城】'
      run: |
        cd ~/scripts
        node jd_5g.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        UN_SUBSCRIBES: ${{ secrets.UN_SUBSCRIBES }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}

    - name: '运行 【京东手机狂欢城】'
      run: |
        cd ~/scripts
        node jd_818.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        UN_SUBSCRIBES: ${{ secrets.UN_SUBSCRIBES }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}

    - name: '运行 【京东秒秒币】'
      run: |
        cd ~/scripts
        node jd_ms.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}

    - name: '运行 【京东压岁钱】'
      run: |
        cd ~/scripts
        node jd_newYearMoney.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}

    - name: '运行 【京东取关商品】'
      run: |
        cd ~/scripts
        node jd_unsubscribe.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        UN_SUBSCRIBES: ${{ secrets.UN_SUBSCRIBES }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}