# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 间隔4小时任务

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0,4,8,12,16,20 * * *'
  watch:
    types: started
  repository_dispatch:
    types: fruit
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      run: |
        git clone ${{ secrets.GIT_CLONE_URL }} ~/scripts
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install
      run: |
        cd ~/scripts
        npm install

    - name: '运行 【宠汪汪积分兑换京豆】'
      run: |
        cd ~/scripts
        node jd_joy_reward.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        JD_JOY_REWARD_NOTIFY: ${{ secrets.JD_JOY_REWARD_NOTIFY }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        BARK_PUSH: ${{ secrets.BARK_PUSH }}
        BARK_SOUND: ${{ secrets.BARK_SOUND }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}

    - name: '运行 【东东农场】'
      run: |
        cd ~/scripts
        node jd_fruit.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        BARK_PUSH: ${{ secrets.BARK_PUSH }}
        FRUITSHARECODES: ${{ secrets.FRUITSHARECODES }}
        FRUIT_BEAN_CARD: ${{ secrets.FRUIT_BEAN_CARD }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        FRUIT_NOTIFY_CONTROL: ${{ secrets.FRUIT_NOTIFY_CONTROL }}
        BARK_SOUND: ${{ secrets.BARK_SOUND }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
    - name: '运行 【京喜农场】'
      run: |
          cd ~/scripts
          node jd_jxnc.js
      env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          FRUITSHARECODES: ${{ secrets.FRUITSHARECODES }}
          FRUIT_BEAN_CARD: ${{ secrets.FRUIT_BEAN_CARD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          FRUIT_NOTIFY_CONTROL: ${{ secrets.FRUIT_NOTIFY_CONTROL }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}

    - name: '运行 【宠汪汪偷好友狗粮与积分】'
      run: |
        cd ~/scripts
        node jd_joy_steal.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        JOY_HELP_FEED: ${{ secrets.JOY_HELP_FEED }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        BARK_PUSH: ${{ secrets.BARK_PUSH }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        BARK_SOUND: ${{ secrets.BARK_SOUND }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}

    - name: '运行 【京喜财富岛】'
      run: |
        cd ~/scripts
        node jd_jxcfd.js
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
        JD_DEBUG: ${{ secrets.JD_DEBUG }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        BARK_PUSH: ${{ secrets.BARK_PUSH }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        BARK_SOUND: ${{ secrets.BARK_SOUND }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}

    - name: '运行 【京东直播】'
      run: |
          cd ~/scripts
          node jd_live.js
      env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          MARKET_COIN_TO_BEANS: ${{ secrets.MARKET_COIN_TO_BEANS }}
          MARKET_REWARD_NOTIFY: ${{ secrets.MARKET_REWARD_NOTIFY }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}

    - name: '运行 【京东摇钱树】'
      run: |
          cd ~/scripts
          node jd_moneyTree.js
      env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}

    - name: '运行 【东东萌宠】'
      run: |
          cd ~/scripts
          node jd_pet.js
      env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          PETSHARECODES: ${{ secrets.PETSHARECODES }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          PET_NOTIFY_CONTROL: ${{ secrets.PET_NOTIFY_CONTROL }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}

    - name: '运行 【东东超市】'
      run: |
          cd ~/scripts
          node jd_superMarket.js
      env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          jdSuperMarketUpgrade: ${{ secrets.SUPERMARKET_UPGRADE }}
          jdBusinessCircleJump: ${{ secrets.BUSINESS_CIRCLE_JUMP }}
          SUPERMARKET_SHARECODES: ${{ secrets.SUPERMARKET_SHARECODES }}
          jdSuperMarketLottery: ${{ secrets.SUPERMARKET_LOTTERY }}

    - name: '运行 【京东取关商品】'
      run: |
          cd ~/scripts
          node jd_unsubscribe.js
      env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          UN_SUBSCRIBES: ${{ secrets.UN_SUBSCRIBES }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}