# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 直播间红包雨

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11,12,13 * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: necklace
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone ${{ secrets.GIT_CLONE_URL }} ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install

      - name: '运行 【直播间红包雨】'
        run: |
          cd ~/scripts
          node jd_live_redrain2.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}